# MPLAB IDE generated this makefile for use with GNU make.
# Project: delay.mcp
# Date: Sat Mar 13 11:18:03 2010

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

delay.lib : delay.o
	$(AR) /c "delay.lib" "delay.o"

delay.o : delay.c
	$(CC) -p=18F4580 /i"C:\MCC18\h" "delay.c" -fo="delay.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "delay.o" "delay.lib"

